name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
          apk add make
          apk add imagemagick
          make
      
    - uses: actions/upload-artifact@v2
      with:
        name: PDF
        path: glorybound.pdf

